-- Convert time columns from TIMESTAMP to DATETIME
-- Run this once on the existing MySQL database.

ALTER TABLE products
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN deleted_at DATETIME NULL;

ALTER TABLE product_variants
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE product_images
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE product_categories
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE customer_tiers
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE customers
  MODIFY COLUMN last_login_at DATETIME NULL,
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN deleted_at DATETIME NULL;

ALTER TABLE orders
  MODIFY COLUMN paid_at DATETIME NULL,
  MODIFY COLUMN confirmed_at DATETIME NULL,
  MODIFY COLUMN shipping_at DATETIME NULL,
  MODIFY COLUMN delivered_at DATETIME NULL,
  MODIFY COLUMN completed_at DATETIME NULL,
  MODIFY COLUMN cancelled_at DATETIME NULL,
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE order_items
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE cart_items
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE addresses
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE transactions
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE reviews
  MODIFY COLUMN replied_at DATETIME NULL,
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE review_images
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE order_status_history
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE contact_messages
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE audit_logs
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE inventory_histories
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE banners
  MODIFY COLUMN start_date DATETIME NULL,
  MODIFY COLUMN end_date DATETIME NULL,
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE coupons
  MODIFY COLUMN start_date DATETIME NOT NULL,
  MODIFY COLUMN end_date DATETIME NOT NULL,
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE coupon_usages
  MODIFY COLUMN used_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE notifications
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE shipping_tracking
  MODIFY COLUMN estimated_delivery DATETIME NULL,
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE site_settings
  MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE product_shops
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE vouchers
  MODIFY COLUMN start_at DATETIME NULL,
  MODIFY COLUMN end_at DATETIME NULL,
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;
